-- Cellar metadata and an immutable, private stock-movement ledger.
alter table public.wines add column if not exists emplacement text;
alter table public.wines add column if not exists date_achat date;
alter table public.wines add column if not exists vendeur text;
alter table public.wines add column if not exists a_racheter boolean not null default false;

alter table public.wines_archive add column if not exists emplacement text;
alter table public.wines_archive add column if not exists date_achat date;
alter table public.wines_archive add column if not exists vendeur text;
alter table public.wines_archive add column if not exists a_racheter boolean not null default false;

create table if not exists public.wine_movements (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  wine_id bigint,
  wine_archive_id bigint,
  type text not null check (type in ('achat','consommation','cadeau_recu','offert','vendu','casse_perte','transfert','correction','restauration')),
  quantite integer not null check (quantite > 0),
  variation integer not null,
  commentaire text,
  emplacement_source text,
  emplacement_destination text,
  created_at timestamptz not null default now(),
  constraint wine_movements_variation_check check (abs(variation) = quantite)
);

alter table public.wine_movements enable row level security;
drop policy if exists "Users manage their own wine movements" on public.wine_movements;
create policy "Users manage their own wine movements" on public.wine_movements
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
revoke all on public.wine_movements from anon;
grant select, insert, update, delete on public.wine_movements to authenticated;
grant usage, select on sequence public.wine_movements_id_seq to authenticated;
create index if not exists wine_movements_user_created_idx on public.wine_movements(user_id, created_at desc);
